require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - '.git/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'tmp/*'
    - 'test/**/*'
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false 

Rails/HasAndBelongsToMany:
  Enabled: false