default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mysqlpass
  host: localhost

development:
  <<: *default
  database: chatdev

test:
  <<: *default
  database: chattest

production:
  <<: *default
  database: chatprod

